### ISSUE TITLE
How to use account[(zero)] for large account(AccountLoader<'info, DataHolder>)?

### ISSUE THREAD

**Issue by julbh** [solana-developers/anchor-zero-copy-example#1]
I appreciate you created this example.

I want to use large account to take around 2.3 SOL (~40KB).
So I tried zero_copy using this example.
But I can't set fixed size for the account. DataHolder accounts should have different size(enough size) for the user param. So that it can reduce the rent of SOL.

I changed this.
`
        #[account(init, seeds = [b"data_holder_zero_copy_v0", 
        signer.key().as_ref()], 
        bump, 
        payer=signer, 
        space= 10 * 1024 as usize)]
        pub data_holder: AccountLoader<'info, DataHolder>,
`
to
`
#[account(zero_copy)]
#[repr(C)]
pub struct DataHolder{
    pub key: Pubkey,
    pub users: [Pubkey; 10000],
}

#[account(zero)]
pub data_holder: AccountLoader<'info, DataHolder>,
`
I sent this instruction after creating the account in web3.js
`
anchor.web3.SystemProgram.createAccount({
    fromPubkey: creatorKeypair.publicKey,
    newAccountPubkey: dataAccount.publicKey,
    lamports: await connection.getMinimumBalanceForRentExemption(dataSize),
    space: dataSize,
    programId: program.programId,
  });
`
As a result, I got this error.
`> Program log: AnchorError occurred. Error Code: AccountDiscriminatorMismatch. Error Number: 3002. Error Message: 8 byte discriminator did not match what was expected.`

Could you help me with this problem? Thanks.

**Comment by julbh** [comment]
Resolved. Use `load_init()` to initialize the account.

**Comment by Woody4618** [comment]
Sorry i didn't get to this earlier. I was traveling. Nice that you figured it out 👍 
Can also always ask questions on https://solana.stackexchange.com/
