### ISSUE TITLE
Arbitrary size of Account with zero_copy

### ISSUE THREAD

**Issue by CryptoCooker** [solana-developers/anchor-zero-copy-example#2]
I want to make the account like this.
```
#[account(zero_copy)]
#[repr(C)]
pub struct LargeData{
 pub accounts: Vec<Pubkey>,
}
```

But it throws error. Any solution for this problem?

**Comment by Woody4618** [comment]
When using zero copy you need to have constant size structs. Try use an array instead. Please use [solana.stackexcahnge ](https://solana.stackexchange.com/) for development support in the future.
