### ISSUE TITLE
Anchor build error

### ISSUE THREAD

**Issue by Lu-Derik** [solana-developers/anchor-zero-copy-example#4]
While I build this program, I received following error. But all the test passed. Can I just ignore the error? And how to silence this error? Thanks! 

ldru@sol-u20:~/solana/anchor-zero-copy-example$ anchor build
Error: Function _ZN9zero_copy9__private8__global25initialize_hit_stack_size17hfd204c16fd2dd2d9E Stack offset of 7416 exceeded max offset of 4096 by 3320 bytes, please minimize large stack variables
Error: Function _ZN121_$LT$zero_copy..InitializeHitStackSize$u20$as$u20$anchor_lang..Accounts$LT$zero_copy..InitializeHitStackSizeBumps$GT$$GT$12try_accounts17h5344bc6dcbd31490E Stack offset of 8432 exceeded max offset of 4096 by 4336 bytes, please minimize large stack variables
Error: Function _ZN75_$LT$zero_copy..HitStackSize$u20$as$u20$anchor_lang..AccountDeserialize$GT$25try_deserialize_unchecked17h360db2c924820e7eE Stack offset of 8792 exceeded max offset of 4096 by 4696 bytes, please minimize large stack variables
    Finished release [optimized] target(s) in 0.16s
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.18s
     Running unittests src/lib.rs (/home/ldru/solana/anchor-zero-copy-example/target/debug/deps/zero_copy-e3917a4579d7ba24)
ldru@sol-u20:~/solana/anchor-zero-copy-example$

**Comment by Woody4618** [comment]
This error is there to show that you will hit the stack size limits if you have too big structs. Its just an example. In production code its highly recommended to not have any of these warnings. They will most likely cause runtime errors.
